# action goal request srv
float32[3] init_config_tran
float32[3] init_config_rot
---
# action result srv
float32[3] final_config_tran
float32[3] final_config_rot
---
# action feedback std_msg
float32[3] joint_error_tran
float32[3] joint_error_rot